data_spliting: "pos_split"
loss: "CrossentropyLoss"
arcface: false # if true, loss needs to be "CrossentropyLoss"
margin: 0.1
scale: 16
model_name: "ClassCNN1"
batch_size: 1024
input_type: "raw"
data_type: "not complex"
class_hidden_size: 64
conv_features1_nb: 20
conv_features2_nb: 20
conv_kernel1_size: 15
conv_kernel2_size: 6
conv_layers_nb: 2
class_layers_nb: 1
stride_size: 2
tail_fc_layers_nb: 1
pooling_kernel_size: 2
pooling_stride_size: 2
data_limit: 500000
data_test_rate: 0.01
datafile: "data/Messung_9/messung9.raw_data.npy"
device: "cuda"
dropout_value: 0
expender_out: 138
feature_norm: "none"
flat_data: true
labelfile: "data/Messung_9/messung9.raw_labels.npy"
latent_dimention: 128
learning_rate: 0.001
lr_limit: 0.0001
nb_epochs: 10000
noise_amount: 0
num_dev: 9
num_pos: 48
optimizer: "Adam"
padding_size: 1
patience: 50
plotting: false
set_parameters: "params.set_parameters"
sheduler: "plateau"
signal_length: 250
split_train_ratio: 0.8
test_interval: 10
use_extender: false
save_model: true
use_gpu: true
use_wandb: true
validation_dev: 0
validation_pos: [4, 5]
verbose: true
warmup_steps: 50
window_size: 16