data_spliting: "pos_exlus"
loss: "complex_crossentropy"
model_name: "ComplexClassCNN1"
input_type: "fft_complex"
additional_samples: 2
multiple_test_measurements: true
multiple_train_positions: true
batch_size: 256
class_hidden_size: 253
class_layers_nb: 1
conv_features1_nb: 82
conv_features2_nb: 33
conv_kernel1_size: 10
conv_kernel2_size: 6
conv_layers_nb: 3
pooling_kernel_size: 4
pooling_stride_size: 2
data_limit: 500000
data_test_rate: 0.1
datafile: "../data/Messung8/messung8.2_data.npy"
device: "cuda"
dropout_value: 0
expender_out: 138
feature_norm: "layer"
flat_data: true
labelfile: "../data/Messung8/messung8.2_labels.npy"
latent_dimention: 156
learning_rate: 0.001
lr_limit: 0.0001
nb_epochs: 10000
noise_amount: 0
num_dev: 13
num_pos: 21
optimizer: "Adam"
padding_size: 1
patience: 50
plotting: false
set_parameters: "params.set_parameters"
sheduler: "plateau"
signal_length: 301 # 41
split_train_ratio: 0.8
stride_size: 1 # 2
tail_fc_layers_nb: 2
test_interval: 1000
use_extender: false
use_gpu: true
use_wandb: true
validation_dev: 0
validation_pos: 5
verbose: true
warmup_steps: 50
window_size: 16