data_spliting: "pos_test"
loss: "vicreg" 
model_name: "Transformer3"
batch_size: 32
class_hidden_size: 256
class_layers_nb: 1
conv_features1_nb: 32
conv_features2_nb: 30
conv_kernel1_size: 2
conv_kernel2_size: 2
conv_layers_nb: 3
data_limit: -1
data_test_rate: 0.1
datafile: "/srv/public/Thibaud/datasets/ultrasec/Messung_9/messung9.2_data.npy"
device: "cuda"
dropout_value: 0
expender_out: 64
expender_layers_nb: 1
expender_hidden_size: 256
feature_norm: "layer"
flat_data: false
labelfile: "/srv/public/Thibaud/datasets/ultrasec/Messung_9/messung9.2_labels.npy"
latent_dimention: 32
learning_rate: 0.001
lr_limit: 0.0001
lambda_triplet: 1
lambda_class: 10
nb_epochs: 10000
noise_amount: 0
num_dev: 9
num_pos: 48
optimizer: "Adam"
padding_size: 0
patience: 100
plotting: false
set_parameters: "params.set_parameters"
sheduler: "plateau"
signal_length: 200
split_train_ratio: 0.8
stride_size: 2
tail_fc_layers_nb: 2
test_interval: 100
trans_embedding_size: 64
trans_head_nb: 2
trans_layer_nb: 3
trans_hidden_nb: 32
use_extender: true
use_gpu: true
use_wandb: true
validation_dev: 0
validation_pos: 5
verbose: true
warmup_steps: 50
window_size: 16
data_type: "not complex"
data_use_position: false