data_spliting: "pos_test"
loss: "crossentropy" 
model_name: "ClassCNN1"
input_type: "raw"
additional_samples: 4 #2
same_positions: false
batch_size: 360 # (for ce: only batch_size//(additional_samples+1) passes through the model) (for vicreg: num_dev*(additional_samples+1)*2*x (x should be even))
class_hidden_size: 256
class_layers_nb: 1
conv_features1_nb: 32
conv_features2_nb: 30
conv_kernel1_size: 2
conv_kernel2_size: 2
conv_layers_nb: 3
data_limit: -1
data_test_rate: 0.1
datafile: "../data/Messung9/messung9.2_data.npy"
device: "cuda"
dropout_value: 0
expender_out: 128
expender_layers_nb: 1
expender_hidden_size: 256
feature_norm: "layer"
flat_data: true
labelfile: "../data/Messung9/messung9.2_labels.npy"
latent_dimention: 450
learning_rate: 0.001
lr_limit: 0.0001
lambda_triplet: 1
lambda_class: 10
lambda_distance: 11    #14
lambda_std: 4        #1.2
lambda_cov: 4 
nb_epochs: 10000
noise_amount: 0
num_dev: 9 #9
num_pos: 48 #48
optimizer: "Adam"
padding_size: 0
patience: 100
plotting: false
set_parameters: "params.set_parameters"
sheduler: "plateau"
signal_length: 1000
split_train_ratio: 0.8
stride_size: 2
tail_fc_layers_nb: 2
test_interval: 500
trans_embedding_size: 16
trans_head_nb: 3
trans_layer_nb: 3
trans_hidden_nb: 64
use_extender: true
use_gpu: true
use_wandb: false
validation_dev: 0
validation_pos: [5]
verbose: true
warmup_steps: 50
window_size: 16
data_type: "not complex"
data_use_position: false