data_spliting: "pos_split"
loss: "CrossentropyLoss"
arcface: false # if true, loss needs to be "CrossentropyLoss"
arcface_margin: 0.1
arcface_scale: 16
model_name: "ViT"
batch_size: 512
input_type: "spectrogram"
data_type: "not complex"
additional_samples: 0 # how many samples to add
same_positions: false # if true, the same positions are used for all additional samples
spectrogram_window_size: 32
data_limit: -1 
data_test_rate: 0.01
datafile: "/srv/public/Thibaud/datasets/ultrasec/Messung_9/messung9.raw.3_data.npy"
device: "cuda"
dropout_value: 0
expender_out: 128
expender_layers_nb: 1
expender_hidden_size: 256
feature_norm: "layer"
flat_data: true
labelfile: "/srv/public/Thibaud/datasets/ultrasec/Messung_9/messung9.raw.3_labels.npy"
latent_dimention: 128
learning_rate: 0.001
lr_limit: 0.0001
lambda_triplet: 1
lambda_class: 10
lambda_distance: 11    #14
lambda_std: 4        #1.2
lambda_cov: 4 
nb_epochs: 10000
noise_amount: 0
num_dev: 13
num_pos: 48
optimizer: "Adam"
patience: 100
plotting: false
set_parameters: "params.set_parameters"
sheduler: "combi"
warmup_steps: 20
signal_length: 250
split_train_ratio: 0.8
test_interval: 10
trans_embedding_size: 32
trans_head_nb: 6
trans_layer_nb: 2
trans_hidden_nb: 32
use_extender: false
use_gpu: true
use_wandb: true
validation_dev: 0
validation_pos: [5]
verbose: true
window_size: 8 #16
data_use_position: false